### ISSUE TITLE
Cops car is not rendered on damage gallery

### ISSUE THREAD

**Issue by rafalp** [dethrace-labs/dethrace#208]
Finish race with cop car and go to damage gallery, it won't be displayed:

<img width="1440" alt="Zrzut ekranu 2022-10-10 o 00 04 51" src="https://user-images.githubusercontent.com/750553/194781618-42c3775b-6114-4f58-b642-10c213134612.png">
<img width="1440" alt="Zrzut ekranu 2022-10-10 o 00 04 53" src="https://user-images.githubusercontent.com/750553/194781622-7d38dac5-9cd8-4c82-8a33-362c3375f402.png">

**Comment by zear** [comment]
@madebr @dethrace-labs 
This happens, because `BrModelUpdate` nukes vertices for the Squad Car's model:
https://github.com/dethrace-labs/dethrace/blob/889e7ba4102a8bb0dba9699bd653ecf15baa374b/src/BRSRC13/CORE/V1DB/prepmesh.c#L683-L694

Squad Car is a bit special, because it is the only car that doesn't have damage model [1]. As such, the code deals with it explicitly:

https://github.com/dethrace-labs/dethrace/blob/889e7ba4102a8bb0dba9699bd653ecf15baa374b/src/DETHRACE/common/loading.c#L1690-L1694

Here `pOwner == 3` does not mean `tDriver` type value, but rather the opponent number of the Squad Car.

Same wrong assumptions are made here:
https://github.com/dethrace-labs/dethrace/blob/889e7ba4102a8bb0dba9699bd653ecf15baa374b/src/DETHRACE/common/loading.c#L2230-L2231
and here:
https://github.com/dethrace-labs/dethrace/blob/889e7ba4102a8bb0dba9699bd653ecf15baa374b/src/DETHRACE/common/loading.c#L2238

I don't have the OG assembly to confirm where this issue stems from, but it sounds like the `BR_MODF_KEEP_ORIGINAL | BR_MODF_UPDATEABLE` flags should not have been removed for this model.

When said flags are forcibly set, Squad Car ends up being rendered correctly:
![apc](https://user-images.githubusercontent.com/510643/200447409-2f190018-bce5-45e0-8d78-a44130f2bde2.png)

[1] https://carmageddon.fandom.com/wiki/The_Cops

**Comment by madebr** [comment]
This is also the behavior in OG (tested with `CARM95.EXE`).
A fix can be added using preprocessor define `DETHRACE_FIX_BUGS`.
![DUMP0000](https://user-images.githubusercontent.com/4138939/200608488-5152fc1e-adb0-4900-912a-b7c1dde57158.jpg)
