### ISSUE TITLE
Cannot start dethrace from terminal (Windows)

### ISSUE THREAD

**Issue by madebr** [dethrace-labs/dethrace#351]
From discord:
> strangely enough, on windows 10, running dethrace.exe directly from the explorer window works, but starting it from the command line doesn't :
> ```
> D:\Carmageddon>Dethrace version: 8051ca2
> Using root directory:
> [PANIC] Harness_Init Failed to chdir. Error is Invalid argument
> ```

**Comment by madebr** [comment]
The original issue is about Macos finder running applications from `/` instead of the directory containing the executable.

You're using a "macosx bundle", which our cmake script does not support at all.
Somebody with an app should modify cmake + sources to add that.
CMake has [`MACOSX_BUNDLE`](https://cmake.org/cmake/help/latest/prop_tgt/MACOSX_BUNDLE.html).

A complication with macosx bundles is that for legal reasons, we cannot bundle game resources with an app bundle.

**Comment by PierreMarieBaty** [comment]
Defaulting root_dir to "." when neither the DETHRACE_ROOT_DIR envvar is 
set nor OS_Dirname(argv[0]) fails to return a directory when argv[0] is 
just an executable name does prevent the issue described here, actually.

I understand and agree that proprietary game resources can't be 
*distributed* in a macOS app bundle, but the end user is still allowed 
to copy them there. That's what the DosBox .app bundle does. Dethrace 
could take advantage of that maybe?

I don't use the CMake script. I made my own build script in bourne shell 
for dethrace for POSIX platforms, so that I can compile the game with 
just a compiler and a linker as a requirement (and of course the needed 
system libraries). Sorry for diverging from the mainstream :/

**Comment by madebr** [comment]
No need to say sorry.
If somebody with a mac and knowledge of CMake comes along, (s)he's free to add this support.

**Comment by dethrace-labs** [comment]
Fixed by https://github.com/dethrace-labs/dethrace/pull/381
